window.AdminMagic = (function() {
    let pendingChange = null;

    function process() {
        const input = document.getElementById('magic-prompt').value.toLowerCase();
        if (!input) return;

        const draft = window.AdminDB.getDraft();
        const resultEl = document.getElementById('magic-result');
        const outputEl = document.getElementById('magic-output');
        
        // Very basic mock heuristic parser for V1
        pendingChange = null;

        if (input.includes('add') && input.includes('sound')) {
            // "Add a thunderstorm sound with a ⛈️ icon"
            const nameMatch = input.match(/(?:add a|add) ([\w\s]+) sound/i);
            const iconMatch = input.match(/(?:with a|icon) ([\up{Emoji}\uFE0F\u200D]+)/u);
            
            const newSound = {
                id: 'magic_' + Date.now(),
                name: nameMatch ? capitalize(nameMatch[1].trim()) : 'New Sound',
                description: 'Generated by Magic Editor',
                icon: '✨', // Default
                file: 'placeholder.mp3',
                enabled: true,
                order: (draft.sounds.length || 0) + 1
            };

            // Emojis are hard to parse via regex accurately without backend LLMs, 
            // but we can fake it for the demo if they literally paste an emoji.
            const emojiRegex = /[\u{1F300}-\u{1F9FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}]/u;
            const emojiFound = input.match(emojiRegex);
            if (emojiFound) {
                newSound.icon = emojiFound[0];
            }

            pendingChange = {
                type: 'ADD_SOUND',
                data: newSound
            };
            
            outputEl.innerText = `PROPOSED CHANGE\n\nAction: Add Sound\nName: ${newSound.name}\nIcon: ${newSound.icon}\nDescription: ${newSound.description}\nStatus: Enabled`;
            resultEl.classList.remove('hidden');
            
        } else if (input.includes('move') || input.includes('hide')) {
            outputEl.innerText = "PROPOSED CHANGE\n\nAction: Modify Layout\nDetails: Adjusting section visibility/order based on instruction.";
            pendingChange = { type: 'LAYOUT_UPDATE' };
            resultEl.classList.remove('hidden');
        } else {
            outputEl.innerText = "ERROR:\nCould not understand intent. Try 'Add a [name] sound with a [emoji] icon.' Note: Full AI generation requires Cloud Functions backend.";
            pendingChange = null;
            resultEl.classList.remove('hidden');
        }
    }

    function capitalize(s) {
        return s.charAt(0).toUpperCase() + s.slice(1);
    }

    function apply() {
        if (!pendingChange) return;
        
        const draft = window.AdminDB.getDraft();

        if (pendingChange.type === 'ADD_SOUND') {
            draft.sounds.push(pendingChange.data);
            window.AdminUI.renderSounds();
        }

        window.AdminDB.markModified();
        document.getElementById('magic-prompt').value = '';
        document.getElementById('magic-result').classList.add('hidden');
        pendingChange = null;
    }

    return { process, apply };
})();
